# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'Simulate rolling a dice and getting the sum
#'
#'This function rolls dice and returns each different roll of the dice. If
#'asked to roll two dice, this will return a numeric vector representing the
#'value of each dice.
#'
#'@name diceRoll
#'
#'
#'@param sides An integer representing the number of sides on the dice
#'@param numDice The number of dice of size 'sides' to be rolled
#'@return A number representing the sum of the dice rolled.
#'@examples
#'diceRoll(6,1)
#'diceRoll(6,2)
#'diceRoll(100,2)
#'@export
diceRoll <- function(sides = 6L, numDice = 2L) {
    .Call(`_partyGames_diceRoll`, sides, numDice)
}

#'Simulate rolling a dice and getting the sum
#'
#'This function rolls dice and returns the sum of the dice. The default function
#'rolls two six-sided dice.
#'
#'@name diceSum
#'
#'
#'@param sides An integer representing the number of sides on the dice
#'@param numDice The number of dice of size 'sides' to be rolled
#'@return A number representing the sum of the dice rolled.
#'@examples
#'diceSum(6,1)
#'diceSum(6,2)
#'diceSum(100,2)
#'@export
diceSum <- function(sides = 6L, numDice = 2L) {
    .Call(`_partyGames_diceSum`, sides, numDice)
}

#'Play a White Elephant Game with dice
#'
#'Simulates a White Elephant party game. The gift starts at position "1" and
#'each player rolls a dice. For each number rolled, the present moves around the
#'circle that many positions in a counter-clockwise fashion.
#'
#'
#'
#'@name dieElephant
#'
#'
#'@param n Number of participants in the game
#'@param sides Number of sides the dice have
#'@param numDice Number of dice to be rolled
#'
#'@return A list containing the final position of the present and a vector
#'representing the movement of the present.
#'
#'@examples
#'# 10 people playing with a six-sided die
#'dieElephant(10, 6, 1)
#'
#'# 20 people playing with two six-sided dice
#'dieElephant(20, 6, 2)
#'
#'@export
NULL

dieElephant <- function(n, sides, numDice) {
    .Call(`_partyGames_dieElephant`, n, sides, numDice)
}

#'Play a White Elephant Game with a coin
#'
#'Simulates a White Elephant party game. The gift starts at position "1" and
#'proceeds to move around the circle as each person flips a coin. If heads, the
#' present moves to the left. If tails, the present moves to the right.
#'
#'
#'To further elaborate on the rules of the game, if the player in position "1"
#'flips tails, the player to his right is sitting in position "2". If he flips
#'heads, the player to the left of position "1" is sitting in the last position.
#'
#'@name leftRightElephant
#'
#'
#'@param n Number of participants in the game
#'@param pheads The probability of heads, or moving the present to the left. Cannot
#'be a `NULL` value
#'
#'@return A list containing the final position of the present and a vector
#'representing the movement of the present (1 is a pass to the right, and -1
#'is a pass to the left).
#'
#'@examples
#'# 10 people playing with a fair coin
#'leftRightElephant(10, 0.5)
#'
#'# 20 people playing with an unfair coin
#'leftRightElephant(20, 0.9)
#'
#'@export
leftRightElephant <- function(n, pheads) {
    .Call(`_partyGames_leftRightElephant`, n, pheads)
}

#'Play a White Elephant Game with dice and a coin
#'
#'Simulates a White Elephant party game. The gift starts at position "1" and
#'each player rolls dice and flips a coin. If the coin is heads, the present
#'gets passed to the left however many seats the dice have shown. If the coin is
#'tails, the present gets passed to the right however many seats the dice show.
#'
#'
#'@name lrDieElephant
#'
#'
#'@param n Number of participants in the game
#'@param pheads The probability of heads, or passing the present to the left
#'@param sides Number of sides the dice have
#'@param numDice Number of dice to be rolled
#'
#'@return A list containing the final position of the present and a vector
#'representing the movement of the present, where negative numbers represent
#'movement to the left and postive number represent movement to the right.
#'
#'@examples
#'# 10 people playing with a six sided dice and a fair coin
#'lrDieElephant(10, 0.5, 6, 1)
#'
#'# 20 people playing with two six-sided dice and an unfair coin (pheads = 0.7)
#'lrDieElephant(20, 0.7, 6, 2)
#'
#'@export
NULL

lrDieElephant <- function(n, pheads, sides, numDice) {
    .Call(`_partyGames_lrDieElephant`, n, pheads, sides, numDice)
}

#'Play a game of Monopoly under specific circumstances
#'
#'This function allows you to look at and emulate playing a game of Monopoly
#'with a single player. This simulation does not keep track of money or which
#'properties that you buy, but instead rolls dice for a specified number of
#'turns and returns information specifying how many times each space was landed
#'on by the player during the game and how many times doubles were rolled during
#'the game.
#'
#'@name monopoly
#'
#'
#'@param turns An integer representing the max number of turns to be played
#'@param sides An integer representing the size of dice to be rolled. Default is a six sided dice
#'@param numDice The number of dice of size 'sides' to be rolled. Default is two dice.
#'@return A list of two vectors representing the number of times each space was
#'landed on and the number of times doubles were rolled.
#'@export
NULL

monopoly <- function(turns = 500L, sides = 6L, numDice = 2L) {
    .Call(`_partyGames_monopoly`, turns, sides, numDice)
}

#'Play a White Elephant Game with dice and a coin
#'
#'Simulates a White Elephant party game. The gift starts at position "1" and
#'each player rolls dice and flips a randomly chosen coin from two available.
#'If the coin is heads, the present gets passed to the left however many seats
#'the dice have shown. If the coin is tails, the present gets passed to the
#'right however many seats the dice show.
#'
#'
#'@name twoCoinDieElephant
#'
#'
#'@param n Number of participants in the game
#'@param pheads1 The probability of heads, or passing the present to the left if using the first coin
#'@param pheads2 The probability of heads, or passing the present to the left if using the second coin
#'@param sides Number of sides on the dice
#'@param numDice Number of dice to be rolled
#'
#'@return A list containing the final position of the present and a vector
#'representing the movement of the present, where negative numbers represent
#'movement to the left and positive number represent movement to the right.
#'
#'@examples
#'# 10 people playing with a six sided dice and a fair coin and and unfair coin
#'twoCoinDieElephant(10, 0.5, 0.7, 6, 1)
#'
#'# 20 people playing with two six-sided dice and two unfair coins (pheads1 = 0.3, pheads2 = 0.7)
#'twoCoinDieElephant(20, 0.3, 0.7, 6, 2)
#'
#'@export
NULL

twoCoinDieElephant <- function(n, pheads1, pheads2, sides, numDice) {
    .Call(`_partyGames_twoCoinDieElephant`, n, pheads1, pheads2, sides, numDice)
}

#'Play a White Elephant Game with two coins
#'
#'Simulates a White Elephant party game. The gift starts at position "1" and
#'each player rolls dice and flips a randomly chosen coin from two available.
#'If the coin is heads, the present gets passed one to the left. If tails, the
#'present gets passed one to the right.
#'
#'
#'@name twoCoinElephant
#'
#'
#'@param n Number of participants in the game
#'@param pheads1 The probability of heads, or passing the present to the left if using the first coin
#'@param pheads2 The probability of heads, or passing the present to the left if using the second coin
#'
#'@return A list containing the final position of the present and a vector
#'representing the movement of the present, where negative numbers represent
#'movement to the left and positive number represent movement to the right.
#'
#'@examples
#'# 10 people playing with a fair coin and an unfair coin
#'twoCoinElephant(10, 0.5, 0.7)
#'
#'# 20 people playing with two unfair coins (pheads1 = 0.3, pheads2 = 0.7)
#'twoCoinElephant(20, 0.3, 0.7)
#'
#'@export
NULL

twoCoinElephant <- function(n, pheads1, pheads2) {
    .Call(`_partyGames_twoCoinElephant`, n, pheads1, pheads2)
}

