# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'Roll a dice
#'
#'This function rolls dice and returns the sum of the dice.
#'
#'@name diceSum
#'
#'
#'@param sides An integer representing the number of sides on the dice
#'@param numDice The number of dice of size 'sides' to be rolled
#'@return A number.
#'@examples
#'diceSum(6,1)
#'diceSum(6,2)
#'diceSum(100,2)
#'@export
diceSum <- function(sides, numDice) {
    .Call('_partyGames_diceSum', PACKAGE = 'partyGames', sides, numDice)
}

