# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'Simulate rolling a dice and getting the sum
#'
#'This function rolls dice and returns the sum of the dice.
#'
#'@name diceSum
#'
#'
#'@param sides An integer representing the number of sides on the dice
#'@param numDice The number of dice of size 'sides' to be rolled
#'@return A number.
#'@examples
#'diceSum(6,1)
#'diceSum(6,2)
#'diceSum(100,2)
#'@export
diceSum <- function(sides, numDice) {
    .Call(`_partyGames_diceSum`, sides, numDice)
}

#'Play a White Elephant Game with dice
#'
#'Simulates a White Elephant party game. The gift starts at position "1" and
#'each player rolls a dice. For each number rolled, the present moves around the
#'circle that many positions in a counter-clockwise fashion.
#'
#'
#'
#'@name dieElephant
#'
#'
#'@param n Number of participants in the game
#'@param sides Number of sides the dice have
#'@param numDice Number of dice to be rolled
#'
#'@return A list containing the final position of the present and a vector
#'representing the movement of the present.
#'
#'@examples
#'# 10 people playing with a six-sided die
#'dieElephant(10, 6, 1)
#'
#'# 20 people playing with two six-sided dice
#'dieElephant(20, 6, 2)
#'
#'@export
NULL

dieElephant <- function(n, sides, numDice) {
    .Call(`_partyGames_dieElephant`, n, sides, numDice)
}

#'Play a White Elephant Game with a coin
#'
#'Simulates a White Elephant party game. The gift starts at position "1" and
#'proceeds to move around the circle as each person flips a coin. If heads, the
#' present moves to the left. If tails, the present moves to the right.
#'
#'
#'To further elaborate on the rules of the game, if the player in position "1"
#'flips tails, the player to his right is sitting in position "2". If he flips
#'heads, the player to the left of position "1" is sitting in the last position.
#'
#'@name leftRightElephant
#'
#'
#'@param n Number of participants in the game
#'@param pheads The probability of heads, or moving the present to the left. Cannot
#'be a `NULL` value
#'
#'@return A list containing the final position of the present and a vector
#'representing the movement of the present (1 is a pass to the right, and -1
#'is a pass to the left).
#'
#'@examples
#'# 10 people playing with a fair coin
#'leftRightElephant(10, 0.5)
#'
#'# 20 people playing with an unfair coin
#'leftRightElephant(20, 0.9)
#'
#'@export
leftRightElephant <- function(n, pheads) {
    .Call(`_partyGames_leftRightElephant`, n, pheads)
}

#'Play a White Elephant Game with dice and a coin
#'
#'Simulates a White Elephant party game. The gift starts at position "1" and
#'each player rolls dice and flips a coin. If the coin is heads, the present
#'gets passed to the left however many seats the dice have shown. If the coin is
#'tails, the present gets passed to the right however many seats the dice show.
#'
#'
#'@name lrDieElephant
#'
#'
#'@param n Number of participants in the game
#'@param pheads The probability of heads, or passing the present to the left
#'@param sides Number of sides the dice have
#'@param numDice Number of dice to be rolled
#'
#'@return A list containing the final position of the present and a vector
#'representing the movement of the present, where negative numbers represent
#'movement to the left and postive number represent movement to the right.
#'
#'@examples
#'# 10 people playing with a six sided dice and a fair coin
#'lrDieElephant(10, 0.5, 6, 1)
#'
#'# 20 people playing with two six-sided dice and an unfair coin (pheads = 0.7)
#'lrDieElephant(20, 0.7, 6, 2)
#'
#'@export
NULL

lrDieElephant <- function(n, pheads, sides, numDice) {
    .Call(`_partyGames_lrDieElephant`, n, pheads, sides, numDice)
}

#'Play a White Elephant Game with dice and a coin
#'
#'Simulates a White Elephant party game. The gift starts at position "1" and
#'each player rolls dice and flips a randomly chosen coin from two available.
#'If the coin is heads, the present gets passed to the left however many seats
#'the dice have shown. If the coin is tails, the present gets passed to the
#'right however many seats the dice show.
#'
#'
#'@name twoCoinDieElephant
#'
#'
#'@param n Number of participants in the game
#'@param pheads1 The probability of heads, or passing the present to the left if using the first coin
#'@param pheads2 The probability of heads, or passing the present to the left if using the second coin
#'@param sides Number of sides on the dice
#'@param numDice Number of dice to be rolled
#'
#'@return A list containing the final position of the present and a vector
#'representing the movement of the present, where negative numbers represent
#'movement to the left and positive number represent movement to the right.
#'
#'@examples
#'# 10 people playing with a six sided dice and a fair coin
#'lrDieElephant(10, 0.5, 6, 1)
#'
#'# 20 people playing with two six-sided dice and an unfair coin (pheads = 0.7)
#'lrDieElephant(20, 0.7, 6, 2)
#'
#'@export
NULL

twoCoinDieElephant <- function(n, pheads1, pheads2, sides, numDice) {
    .Call(`_partyGames_twoCoinDieElephant`, n, pheads1, pheads2, sides, numDice)
}

